blog/urls.py
from django.urls import path,include
from .views import *
from . import views
app_name = 'blog'
urlpatterns = [
    path('edit_form/<int:blog_id>',get_edit_form,name='edit_form'),
    path('dashboard',BlogDashBoard.as_view(),name='dashboard'),
    path('create',BlogCreateView.as_view(),name='blog_create'),
    path('list',BlogList.as_view(),name='blog_list'),
    path('detail/<str:encrypted_pk>/',BlogDetail.as_view(),name='blog_detail'),
    path('manage/',ManageBlog.as_view(),name='manage_blog'),
    path('delete/<int:pk>/',DeleteBlog.as_view(),name='blog_delete'),
    path('',BlogListView.as_view(),name='index_blogs'),
    path('add_comment/<int:post_id>/',add_comment,name='add_comment'),
]

blog_app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('',include('blog.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/blog_app/base.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block title %} Phoenix Base {% endblock %}</title>
    
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    {% block css %}
      
    {% endblock css%}
    
    
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <script src="{% static 'js/bootstrap.min.js' %}"></script>
      {% block js %}
      {% endblock js %}

  </head>

<body>

  <div class="bg-dark col-auto">
    {% include 'blog_app/nav.html'%}
  </div>

  <div class="container-fluid mt-5">
    <div class="row pt-2">
      <div class="col-lg-2 col-12 bg-dark vh-100 ">
        <nav class="nav flex-column">
          <a class="nav-link" href="{% url 'blog:blog_list' %}">Blogs</a>
          <a class="nav-link" href="{% url 'blog:blog_create' %}">Create Blog</a>
          <a class="nav-link" href="{% url 'blog:manage_blog' %}">Manage Blogs</a>
        </nav>
      </div>
      <div class="col-lg-10 col-sm-12 col-12 col-md-10">
        <div class="main-content bg-light"> 
            {% block content %}
            {% endblock %}
        </div>
        {% block pagination %}
        {% if page_obj %}
          {% include 'blog_app/pagination_container.html'%}
        {% endif %}
      {% endblock %}
        
      </div>
      
    </div>
  </div>


 

</body>

</html>

templates/blog_app/landing_page.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Phoenix Base {% endblock %}</title>

    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>

<body>

  <div class="bg-dark col-xs-3">
    {% include 'blog_app/nav.html'%}
  </div>
  <div class="container-fluid mt-5">
    <div class="row pt-2 d-flex justify-content-center align-items-center vh-100">
        <div class="main-content">
          {% block content %}
          {% endblock %}
        </div>
    </div>
  </div>


  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

</body>
</html>

templates/blog_app/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'blog:index_blogs' %}">Phoenix <Base></Base></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          {% if request.user.is_authenticated%}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
          {%else%}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'register' %}">Register</a>
          </li>
          {% endif %}
        </ul>
      </div>
      {% if request.user.is_authenticated%}
      <span class="text-white"> Loggined as {{request.user.username}}</span>
      {% endif %}
    </div>
  </nav>
  

templates/blog_app/pagination_container.html
<div class="pagination-container d-flex justify-content-center align-items-center">
    {% if page_obj.has_other_pages %}
  <div class="btn-group" role="group" aria-label="Item pagination">
      {% if page_obj.has_previous %}
          <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-outline-primary">&laquo;</a>
      {% endif %}
  
      {% for page_number in page_obj.paginator.page_range %}
          {% if page_obj.number == page_number %}
              <button class="btn btn-outline-primary active">
                  <span>{{ page_number }} <span class="sr-only"></span></span>
              </button>
          {% else %}
              <a href="?page={{ page_number }}" class="btn btn-outline-primary">
                  {{ page_number }}
              </a>
          {% endif %}
      {% endfor %}
  
      {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}" class="btn btn-outline-primary">&raquo;</a>
      {% endif %}
  </div>
  {% endif %}
  </div>