blog/urls.py
from django.urls import path,include
from .views import *
from . import views
app_name = 'blog'
urlpatterns = [
    path('edit_form/<int:blog_id>',get_edit_form,name='edit_form'),
    path('dashboard',BlogDashBoard.as_view(),name='dashboard'),
    path('create',BlogCreateView.as_view(),name='blog_create'),
    path('list',BlogList.as_view(),name='blog_list'),
    path('detail/<str:encrypted_pk>/',BlogDetail.as_view(),name='blog_detail'),
    path('manage/',ManageBlog.as_view(),name='manage_blog'),
    path('delete/<int:pk>/',DeleteBlog.as_view(),name='blog_delete'),
    path('',BlogListView.as_view(),name='index_blogs'),
    path('add_comment/<int:post_id>/',add_comment,name='add_comment'),
]

blog_app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('',include('blog.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
# from ckeditor.fields import RichTextField
from django.contrib.auth.models import User

# Create your models here.

class Blog(models.Model):
    title   = models.CharField(max_length=100)
    content = models.TextField(null=True,blank=True)
    created = models.DateTimeField(auto_now_add=True)
    auther  = models.ForeignKey(User,on_delete=models.CASCADE,default=6)
    image   = models.ImageField(upload_to='blog_images/',default='default_image.jpg')

    def __str__(self) -> str:
        return self.title
    

class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='comments')
    auther  = models.ForeignKey(User,on_delete=models.CASCADE)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    parent = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='replies')

blog/forms.py
from django import forms
from .models import Blog,Comment

# views code 

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title','content']
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'Title', 'class': 'form-control'}),
            'content': forms.Textarea(attrs={'placeholder': 'Content', 'class': 'form-control'}),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'placeholder': 'Comment', 'class': 'form-control'}),
        }
        labels = {
            'text': 'Comment',
        }

blog/views.py
from django.shortcuts import render
from django.urls import reverse_lazy    
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.shortcuts import get_object_or_404

from hashids import Hashids

from django.views.generic import ListView,DetailView
from django.views.generic.base import TemplateView
from django.views.generic.edit import CreateView,DeleteView

from .models import Blog
from .forms import  BlogForm

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect

from django.utils.crypto import get_random_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str

# Create your views here.

class BlogDashBoard(TemplateView):
    template_name = "blog_app/base.html"


@method_decorator(login_required,name='dispatch')
@method_decorator(csrf_protect,name='dispatch')
class BlogCreateView(CreateView):
    model           = Blog
    form_class      = BlogForm
    template_name   = 'blog/create_blog.html'
    success_url     = reverse_lazy('blog:blog_list')

    def form_valid(self, form):

        title = form.cleaned_data['title']
        content = form.cleaned_data['content']
        self.cleaned_data = form.cleaned_data

        if Blog.objects.filter(title=title, content=content).exists():
            form.add_error(None, "This blog post already exists.")
            return self.form_invalid(form)
        super().form_valid(form)

        rendered_template = render_to_string('blog/blog_list.html',self.get_context_data())
        return JsonResponse({'blog_data':rendered_template})
    
    def get_context_data(self,**kwargs):
        context = super().get_context_data()
        if self.request.headers.get('x-requested-with') == 'XMLHttpRequest':
            context['blogs'] = Blog.objects.get(title=self.cleaned_data['title'], content=self.cleaned_data['content'])
        else:
            context['blogs'] = Blog.objects.filter(auther=self.request.user)
        return context

    def form_invalid(self, form):
        print(form.errors)
        return super().form_invalid(form)
    
class BlogListView(ListView):
    model = Blog
    template_name = 'blog/front_page.html'
    context_object_name = 'blog_posts'

    
@method_decorator(login_required,name='dispatch')
@method_decorator(csrf_protect,name='dispatch')
class BlogList(ListView):
    model               = Blog
    template_name       = 'blog/list_blogs.html'
    context_object_name = 'blogs'
    paginate_by         = 1

    def get_queryset(self):
        queryset = super().get_queryset()
        filtered_queryset = queryset.filter(auther=self.request.user)

        return filtered_queryset

@method_decorator(login_required,name='dispatch')
@method_decorator(csrf_protect,name='dispatch')
class BlogDetail(DetailView):
    model               = Blog
    template_name       = 'blog/blog_detail.html'
    context_object_name = 'blog'

    def get_object(self, queryset=None):
        encrypted_pk = self.kwargs.get('encrypted_pk')
        hashids = Hashids(salt="test_id",min_length=8)
        blog_id = hashids.decode(encrypted_pk)[0]
        obj = get_object_or_404(Blog,id=blog_id)
        return obj
    
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['comments'] = self.object.comments.all()
        return context

@method_decorator(login_required,name='dispatch')
@method_decorator(csrf_protect,name='dispatch')
class ManageBlog(ListView):
    model               = Blog
    template_name       = 'blog/manage_blog.html'
    context_object_name = 'blogs'
    paginate_by = 1



class DeleteBlog(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:manage_blog')



from django.template.loader import render_to_string
from django.template import RequestContext
from django.views.decorators.csrf import csrf_exempt

@csrf_exempt
def get_edit_form(request,blog_id):

    form_class = BlogForm
    form_class.method = 'POST'
    form_class.action = request.path
    instance = Blog.objects.get(pk=blog_id)

    if request.method == form_class.method:
        form = form_class(request.POST,instance=instance,prefix='form1')
        if form.is_valid():
            form.save()
            return JsonResponse({'message':'Blog Updated successfully..'})
    else:
        form     = form_class(instance=instance,prefix='form1')
        
        html_content = render_to_string('blog/test.html',{'form':form},request)
        return JsonResponse({'html_content': html_content})




from .forms import CommentForm
from django.shortcuts import redirect
def add_comment(request,post_id):
    blog = Blog.objects.get(id=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.blog = blog
            comment.auther = request.user
            comment.save()
            hashids = Hashids(salt="test_id",min_length=8)
            enc_id = hashids.encode(blog.pk)
            return redirect('blog:blog_detail', encrypted_pk=enc_id)
    else:
        form = CommentForm()
    return render(request, 'blog/add_comment.html', {'form': form})

blog/templates/blog/add_comment.html
{% extends 'blog_app/base.html'%}
{%block content%}
<div class="form_container p-5 bg-light row d-flex justify-content-center align-items-center">
    <form method="post" action="{{request.path}}" class="col-sm-6">
        {% csrf_token %}
            {% for field in form %}
                <div class="form-group p-2">
                    <label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                        {% if field.errors %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        {% endif %}
                </div>
            {% endfor %}
            <button type="submit" value="Submit" class="btn btn-success">Submit</button>
    </form>
</div>
{% endblock %}

blog/templates/blog/blog_detail.html
{%extends 'blog_app/base.html' %}
{%block content%}

    <div class="row mt-5" style="display:grid;place-items:center;">
        <div class="blog-detail col-md-6 pt-4">
            <div class="card">
                <div class="card-body">
                    <img src="{{ blog.image.url }}" class="img-fluid" alt="{{ blog.title }}">
                    <h5 class="card-title">{{ blog.title }}</h5>
                    <p class="card-text">{{ blog.content }}</p>
                </div>
                <a href="{%url 'blog:add_comment' blog.id%}" class="btn btn-outline-primary">Add Comment</a>
            </div>
            <div class="comment-container mt-5">
                {% for comment in comments %}
                    <div class="container">
                        <div class="comment p-3 mb-3 bg-light">
                            <img src="https://i.imgur.com/yTFUilP.jpg" alt="" class="rounded-circle" width="40" height="40">
                            <h4>{{comment.auther}}</h4>
                            <span>- {{comment.created_at}}</span>
                            <div class="comment-body">
                                {{ comment.text }}
                                {% for reply in comment.replies.all %}
                                    <div class="reply p-2 bg-secondary text-white">
                                        <img src="https://i.imgur.com/yTFUilP.jpg" alt="" class="rounded-circle" width="40" height="40">
                                        <h4>{{comment.auther}}</h4>
                                        <span>- {{comment.created_at}}</span>
                                        <div class="reply-body">
                                            {{ reply.text }}
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
                
        </div>
    </div>

    <style>
        .comment {
            border: 1px solid #ccc;
            border-radius: 5px;
        }

        .reply {
            margin-left: 20px;
        }
    </style>


{%endblock%}

blog/templates/blog/blog_list.html
<tr>
    <td>{{ blogs.title }}</td>
    <td>{{ blogs.content }}</td>
    <td>
        <a href="" class="btn btn-primary">Edit</a>
    </td>
</tr>

blog/templates/blog/create_blog.html
{%extends 'blog_app/base.html'%}

{% block content %}
<div class="row">
<div class="col-md-8 form_container vh-100 bg-light row d-flex justify-content-center align-items-center">
    <form method="POST" action="{% url 'blog:blog_create'%}" class="col-sm-6 post-form">
        {% csrf_token %}
            {% for field in form %}
                <div class="form-group p-2">
                    <label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {% if field.errors %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                    {% endif %}
                </div>
            {% endfor %}

            {% if form.errors %}
                <ul>
                    {% for field in form %}
                        {% for error in field.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                </ul>
            {% endif %}
        <div class="buttons d-flex justify-content-center align-items-center">
            <button type="submit" class="btn btn-primary">Create</button>
        </div>
    </form>
</div>
<div class="col-md-4">
<div class="vh-100" style="overflow-y: scroll;">
    <table class="table table-striped table-bordered mt-3">
        <thead>
            <tr style="text-align:center;">
                <th>Title</th>
                <th>Content</th>
            </tr>
        </thead>
        <tbody id="postList">
            {% for blog in blogs %}
                <tr>
                    <td>{{ blog.title }}</td>
                    <td>{{ blog.content }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
</div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function() {
        $('.post-form').on('submit', function(event) {
            event.preventDefault();
            $.ajax({
                type: 'POST',
                headers: { 'X-CSRFToken': '{{ csrf_token }}' },
                url: $(this).attr('action'),
                data: $(this).serialize(),
                success: function(response) {
                    $('#postList').prepend(response.blog_data);
                    $(this).find('input[type=text], textarea').val('');
                },
                error: function(error) {
                    console.log(error);
                }
            });
        });
    });
</script>
{% endblock %}

blog/templates/blog/front_page.html
{% extends 'blog_app/landing_page.html'%}
{% load hashid_filters %}
{% block content %}
    <div class="container">
        <div class="row">
            {% for blog in blog_posts %}
            <div class="col-md-6 mb-5">

                <img src="{{ blog.image.url }}" class="card-img-top" alt="{{ blog.title }}">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">{{ blog.title }}</h5>
                        <p class="card-text">{{ blog.content }}</p>
                        <p class="card-text"><small class="text-muted">{{ blog.created }}</small></p>
                        <div class="author-info">
                            <span class="author-name">Published by {{ blog.auther.username }}</span>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

blog/templates/blog/index.html
<!DOCTYPE html> 
<html lang="en"> 

<head> 
	<meta charset="UTF-8"> 
	<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
	<title>Live Calculator</title> 
</head> 

<body> 
	<textarea name="ta" id="results" cols="30" rows="10"> 

	</textarea><br> 
	Enter the expression: <input type="text" id="exp"> 
	<input type="button" id="submit" value="Get Results"> 
	<script> 
		const socket = new WebSocket('ws://localhost:8000/ws/livec/'); 
		socket.onmessage = (e) => { 
			result = JSON.parse(e.data).result; 
			document.getElementById("results").value += "Server: " + result + "\n"; 
		} 

		socket.onclose = (e) => { 
			console.log("Socket closed!"); 
		} 

		document.querySelector('#exp').onkeyup = function (e) { 
			if (e.keyCode === 13) { // enter, return 
				document.querySelector('#submit ').click(); 
			} 
		}; 

		document.querySelector("#submit").onclick = (e) => { 
			inputfield = document.querySelector("#exp") 
			exp = inputfield.value
			alert(exp);
			socket.send(JSON.stringify( 
				{ 
					expression: "2+3" 
				} 
			)) 
			document.querySelector("#results").value += "You: " + exp + "\n"; 
			inputfield.value = ""; 
		} 

	</script> 
</body> 

</html>

blog/templates/blog/list_blogs.html
{%extends 'blog_app/base.html' %}
{% load hashid_filters %}
{% block content %}
    <div class="blogs row mt-5">
        {% for blog in blogs %}
            <div class="col-md-6 mb-3">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title"><a href="{% url 'blog:blog_detail' blog.pk|hashid_encode:blog.title %}">{{ blog.title }}</a></h5>
                        <p class="card-text">{{ blog.content }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

blog/templates/blog/manage_blog.html
{% extends 'blog_app/base.html'%}
{% load static %}
{% block js %}
<script src="{% static 'js/frontend/blog_edit_modal.js' %}"></script>
{% endblock js %}
  
{% block content %}
<div class="container">
    <table class="table table-striped mt-3"> 
        <thead>
            <tr>
                <th>Title</th>
                <th>Content</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for blog in blogs %}
              <tr>
                  <td>{{ blog.title }}</td>
                  <td>{{ blog.content }}</td>
                  <td>
                    
                    
                      <div class="btn-group" role="group" aria-label="First group">
                        <button type="button" class="btn btn-primary edit-button" onclick="open_blog_edit_modal(event,'{{blog.id}}')" blog_edit_url="{% url 'blog:edit_form' blog.id %}">Update</button>
                        <form method="POST" action="{% url 'blog:blog_delete' blog.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger">Delete</button>
                        </form>
                    </div>
                    

                  </td>
              </tr>
            {% endfor %}
        </tbody>
    </table>

</div>
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Edit</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      
      <div class="modal-body">
      </div>
      
    </div>
  </div>
</div>
<style>
  
</style>

{% endblock %}

blog/templates/blog/nnnmm.html
<!DOCTYPE html>
<html>
<head>
    <title>Blog Page</title>
    <script src="https://cdn.socket.io/4.7.5/socket.io.min.js" integrity="sha384-2huaZvOR9iDzHqslqwpR87isEmrfxqyWOF7hr7BY6KG0+hVKLoEXMPUJw3ynWuhO" crossorigin="anonymous"></script>
</head>
<body>
    <div id="blog-content"></div>
    <h1>Client IP Address: {{ request.META.HTTP_USER_AGENT }}</h1>


</body>
<script>
    const socket = io('http://localhost:3000'); // Connect to Node.js server
    socket.on('connect', () => {
        alert('Connected to Socket.io server');
    });
    // socket.on('blogData', (data) => {
    //     document.getElementById('blog-content').innerHTML = data;
    // });
</script>
</html>

blog/templates/blog/table_view.html
{% extends 'blog_app/base.html' %}
{% block content %}
<div class="form_container p-5 bg-light row d-flex justify-content-center align-items-center">
    <table class="table table-striped">
        <tbody>
            <tr>
                {% for key,value in headers.items %}
                    <th>{{value}}</th>
                {%endfor%}
            </tr>
            {% for data in table_data  %}
                <tr>
                    {% for key,value in data.items %}
                        <td>{{value}}</td>
                        {% if forloop.last %}
                            {% if actions %}
                                <td>
                                 
                                    <div class="btn-toolbar mb-3" role="toolbar" aria-label="Toolbar with button groups">
                                        <div class="btn-group mr-2" role="group" aria-label="First group">
                                            {% for key,value in actions.items %}
                                        
                                                {% with action=value %}
                                                    <form method='POST' action="{% url 'blog:blog_delete' data.id %}">
                                                        {% csrf_token %}
                                                        <button type="submit" class="{{action.class}}"><span class="bi-trash"></span> </button>
                                                    </form>
                                                {% endwith %}
                                            {% endfor %}
                                        </div>
                                    </div>
                                </td>
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
        
        
    </table>
</div>
{% endblock %}

blog/templates/blog/test.html
<div class="form_container p-5 bg-light row d-flex justify-content-center align-items-center">
    <form method="{{form.method}}" action="{{request.path}}" class="col-sm-6">
        {% csrf_token %}
            {% for field in form %}
                <div class="form-group p-2">
                    <label class="form-label" for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {% if field.errors %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                    {% endif %}
                </div>
            {% endfor %}
            <button type="submit" value="Submit" class="btn btn-success">Submit</button>
    </form>
</div>